"""Property-based tests for ConfigManager."""

import os
import tempfile
from pathlib import Path
from typing import Dict

import pytest
from hypothesis import given, settings, strategies as st

from alice.core.config import Config, ConfigManager


class TestConfigManagerProperties:
    """Property-based tests for ConfigManager validation."""

    @given(
        missing_vars=st.lists(
            st.sampled_from(["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]),
            min_size=1,
            max_size=3,
            unique=True,
        )
    )
    @settings(max_examples=10)
    def test_property_8_config_validation_rejects_missing_required_variables(
        self, missing_vars
    ):
        """Property 8: Config Validation Rejects Missing Required Variables.

        For any Config_Manager initialization with missing required environment
        variables, validation should fail with a clear error message that does
        not expose the variable names or values.

        **Validates: Requirements 4.2**
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            env_file.write_text("")

            # Set all required vars except the missing ones
            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    original_env[var] = os.environ.pop(var, None)

                # Set only the non-missing vars
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    if var not in missing_vars:
                        os.environ[var] = "test_value"

                # Should raise ValueError
                with pytest.raises(ValueError) as exc_info:
                    ConfigManager(str(env_file))

                # Error message should not expose variable names or values
                error_msg = str(exc_info.value)
                assert "variable(s) not set" in error_msg
                # Should not contain the actual variable names
                for var in missing_vars:
                    assert var not in error_msg

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)

    @given(
        secret_key=st.sampled_from(["groq_api_key", "gemini_api_key", "discord_token"]),
        secret_value=st.text(min_size=1, max_size=50),
    )
    @settings(max_examples=10)
    def test_property_9_config_never_logs_secrets(self, secret_key, secret_value):
        """Property 9: Config Never Logs Secrets.

        For any log message generated by the system, if the message contains a
        configuration value that is marked as secret (API keys, tokens), the
        log should not contain the actual value.

        **Validates: Requirements 4.3**
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"

            # Create env file with all required vars
            env_content = f"""
GROQ_API_KEY=groq_secret_key
GEMINI_API_KEY=gemini_secret_key
DISCORD_TOKEN=discord_secret_token
"""
            env_file.write_text(env_content)

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    original_env[var] = os.environ.pop(var, None)

                # Load config
                config_manager = ConfigManager(str(env_file))

                # Convert to dict (which should exclude secrets)
                config_dict = config_manager.to_dict()

                # Verify secrets are not in the dict
                assert "groq_api_key" not in config_dict
                assert "gemini_api_key" not in config_dict
                assert "discord_token" not in config_dict

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)

    @given(
        invalid_value=st.text(
            min_size=1, max_size=20, 
            alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
        )
    )
    @settings(max_examples=10)
    def test_property_10_config_type_validation(self, invalid_value):
        """Property 10: Config Type Validation.

        For any configuration value with a specified type (integer, URL, boolean),
        if a value of a different type is provided, Config_Manager should reject
        it with a clear error message.

        **Validates: Requirements 4.6**
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"

            # Create env file with invalid integer value
            env_content = f"""
GROQ_API_KEY=test_key
GEMINI_API_KEY=test_key
DISCORD_TOKEN=test_token
GROQ_TIMEOUT_MS={invalid_value}
"""
            env_file.write_text(env_content, encoding='utf-8')

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    original_env[var] = os.environ.pop(var, None)

                # Should raise ValueError for invalid type (non-numeric strings)
                with pytest.raises(ValueError) as exc_info:
                    ConfigManager(str(env_file))
                error_msg = str(exc_info.value)
                assert "Invalid type" in error_msg or "invalid literal" in error_msg

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)


class TestConfigManagerUnit:
    """Unit tests for ConfigManager."""

    def test_config_manager_loads_valid_env(self):
        """Test ConfigManager loads valid environment variables."""
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            env_content = """
GROQ_API_KEY=test_groq_key
GEMINI_API_KEY=test_gemini_key
DISCORD_TOKEN=test_discord_token
GROQ_TIMEOUT_MS=5000
ENVIRONMENT=production
"""
            env_file.write_text(env_content)

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    original_env[var] = os.environ.pop(var, None)

                config_manager = ConfigManager(str(env_file))

                assert config_manager.get("groq_api_key") == "test_groq_key"
                assert config_manager.get("gemini_api_key") == "test_gemini_key"
                assert config_manager.get("discord_token") == "test_discord_token"
                assert config_manager.get("groq_timeout_ms") == 5000
                assert config_manager.get("environment") == "production"

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)

    def test_config_manager_uses_defaults(self):
        """Test ConfigManager uses default values for optional variables."""
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            env_content = """
GROQ_API_KEY=test_groq_key
GEMINI_API_KEY=test_gemini_key
DISCORD_TOKEN=test_discord_token
"""
            env_file.write_text(env_content)

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN", "GROQ_TIMEOUT_MS", "LOG_LEVEL", "ENVIRONMENT"]:
                    original_env[var] = os.environ.pop(var, None)

                config_manager = ConfigManager(str(env_file))

                # Check defaults are used
                assert config_manager.get("groq_timeout_ms") == 30000
                assert config_manager.get("log_level") == "INFO"
                assert config_manager.get("environment") == "dev"

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)

    def test_config_manager_validate_method(self):
        """Test ConfigManager validate method."""
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            env_content = """
GROQ_API_KEY=test_groq_key
GEMINI_API_KEY=test_gemini_key
DISCORD_TOKEN=test_discord_token
"""
            env_file.write_text(env_content)

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    original_env[var] = os.environ.pop(var, None)

                config_manager = ConfigManager(str(env_file))
                assert config_manager.validate() is True

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)

    def test_config_manager_to_dict_excludes_secrets(self):
        """Test ConfigManager to_dict excludes secret values."""
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            env_content = """
GROQ_API_KEY=test_groq_key
GEMINI_API_KEY=test_gemini_key
DISCORD_TOKEN=test_discord_token
"""
            env_file.write_text(env_content)

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    original_env[var] = os.environ.pop(var, None)

                config_manager = ConfigManager(str(env_file))
                config_dict = config_manager.to_dict()

                # Secrets should not be in dict
                assert "groq_api_key" not in config_dict
                assert "gemini_api_key" not in config_dict
                assert "discord_token" not in config_dict

                # Non-secrets should be in dict
                assert "log_level" in config_dict
                assert "environment" in config_dict

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)

    def test_config_manager_invalid_log_level(self):
        """Test ConfigManager rejects invalid log level."""
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            env_content = """
GROQ_API_KEY=test_groq_key
GEMINI_API_KEY=test_gemini_key
DISCORD_TOKEN=test_discord_token
LOG_LEVEL=INVALID
"""
            env_file.write_text(env_content)

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN"]:
                    original_env[var] = os.environ.pop(var, None)

                with pytest.raises(ValueError) as exc_info:
                    ConfigManager(str(env_file))
                assert "Invalid LOG_LEVEL" in str(exc_info.value)

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)

    def test_config_manager_invalid_history_backend(self):
        """Test ConfigManager rejects invalid history backend."""
        with tempfile.TemporaryDirectory() as tmpdir:
            env_file = Path(tmpdir) / ".env"
            env_content = """
GROQ_API_KEY=test_groq_key
GEMINI_API_KEY=test_gemini_key
DISCORD_TOKEN=test_discord_token
HISTORY_BACKEND=invalid
"""
            env_file.write_text(env_content)

            original_env = {}
            try:
                # Clear environment
                for var in ["GROQ_API_KEY", "GEMINI_API_KEY", "DISCORD_TOKEN", "HISTORY_BACKEND", "LOG_LEVEL"]:
                    original_env[var] = os.environ.pop(var, None)

                with pytest.raises(ValueError) as exc_info:
                    ConfigManager(str(env_file))
                assert "Invalid HISTORY_BACKEND" in str(exc_info.value)

            finally:
                # Restore environment
                for var, value in original_env.items():
                    if value is not None:
                        os.environ[var] = value
                    else:
                        os.environ.pop(var, None)
